# Generated by Django 5.0.3 on 2024-03-31 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='elon',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eloncomment',
            name='elon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elon.elon'),
        ),
        migrations.AddField(
            model_name='eloncomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elon',
            name='images',
            field=models.ManyToManyField(related_name='elons', to='elon.elonimages'),
        ),
    ]
