# Generated by Django 5.0.3 on 2024-03-31 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elon', '0003_category_elon_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elon',
            name='category',
            field=models.ManyToManyField(related_name='elon_category', to='elon.category'),
        ),
    ]
