# Generated by Django 5.0.3 on 2024-03-31 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elon', '0004_alter_elon_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elonimages',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
